from collections.abc import Sequence
from typing import Protocol, runtime_checkable

from data_models.patient_demographics import PatientDemographics


@runtime_checkable
class ClinicalNoteAccessorProtocol(Protocol):
    # --- Base methods: implemented by all accessors (Caboodle, FHIR, Fabric) ---
    async def get_patients(self) -> list[str]: ...
    async def get_metadata_list(self, patient_id: str) -> list[dict[str, str]]: ...
    async def read(self, patient_id: str, note_id: str) -> str: ...
    async def read_all(self, patient_id: str) -> list[str]: ...

    # --- Filter methods: implemented by all accessors ---
    async def get_clinical_notes_by_type(
        self, patient_id: str, note_types: Sequence[str]
    ) -> list[dict]: ...

    async def get_clinical_notes_by_keywords(
        self, patient_id: str, note_types: Sequence[str], keywords: Sequence[str]
    ) -> list[dict]: ...

    # --- GYN-specific report/lab methods: implemented by all accessors ---
    async def get_pathology_reports(self, patient_id: str) -> list[dict]: ...

    async def get_radiology_reports(self, patient_id: str) -> list[dict]: ...

    async def get_lab_results(
        self, patient_id: str, component_name: str | None = None
    ) -> list[dict]: ...

    async def get_lab_results_with_notes_fallback(
        self, patient_id: str, component_name: str | None = None,
        keywords: Sequence[str] | None = None,
    ) -> list[dict]: ...

    async def get_tumor_markers(self, patient_id: str) -> list[dict]: ...

    async def get_cancer_staging(self, patient_id: str) -> list[dict]: ...

    async def get_medications(
        self, patient_id: str, order_class: str | None = None
    ) -> list[dict]: ...

    async def get_diagnoses(self, patient_id: str) -> list[dict]: ...

    async def get_patient_demographics(self, patient_id: str) -> PatientDemographics | None: ...
