version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/democlient"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "frontend"
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "ci"
